def prompt_switch_detection(n_images: int) -> str:
    return (
        f"You are a robotic vision analyzer watching a {n_images}-frame video clip of household manipulation tasks.\n"
        f"**Mapping:** Image indices range from 0 to {n_images - 1}.\n\n"
        "### Goal\n"
        "Detect **Atomic Task Boundaries** (Switch Points).\n"
        "A 'Switch' occurs strictly when the robot **completes** interaction with one object and **starts** interacting with a DIFFERENT object.\n\n"
        "### Core Logic (The 'Distinct Object' Rule)\n"
        "1. **True Switch:** Robot releases Object A (e.g., a cup) and moves to grasp Object B (e.g., a spoon). -> MARK SWITCH.\n"
        "2. **False Switch (IMPORTANT):** If the robot is manipulating different parts of the **SAME** object (e.g., folding sleeves then folding the body of the same shirt), this is **NOT** a switch. Treat it as one continuous task.\n"
        "3. **Visual Similarity:** Be careful with objects of the same color. Only mark a switch if you clearly see the robot **physically separate** from the first item before touching the second.\n\n"
        "### Task Context (Optional Prior Knowledge)\n"
        "High-level task:\n"
        "Put the toy cars into the brown basket and put the fruit into the black basket.\n\n"
        "Object inventory (some props may repeat):\n"
        "- Containers:\n"
        "Descriptor : CanonicalRef\n"
        "A brown rectangular bamboo-woven storage basket : brown basket\n"
        "A black rectangular bamboo-woven storage basket : black basket\n"
        "- Fruit:\n"
        "A green round kiwifruit : kiwi\n"
        "Half a kiwifruit with a brown fuzzy skin and a green interior (a kind of ground fruit when look) : kiwi\n"
        "A purple bunch of grapes : grapes\n"
        "Half a red apple with a white interior : apple\n"
        "A yellow avocado with a white center and an orange pit : avocado\n"
        "A green avocado (alligator pear) with a bumpy, textured skin : avocado\n"
        "An orange with a bright orange peel : orange\n"
        "A small round orange-colored citrus fruit with a green stem : orange\n"
        "- Toy cars:\n"
        "A small red toy truck : red car\n"
        "A small red toy car : red car\n"
        "A small gold toy car : gold car\n"
        "A small black toy car : black car\n"
        "Various toy cars : <color> car\n"
        "Rule for Various toy cars: if the car color is identifiable, set CanonicalRef to \"<color> car\" (e.g., blue car, white car). Use a single color word.\n\n"
        "### Canonical Reference Policy\n"
        "1. CanonicalRef is the only allowed name to mention that entity anywhere in the output JSON. ESPECIALLY IN INSTRUCTION!\n" 
        "### Instruction Template Constraint\n"
        "- Each instruction MUST MUST MUST strictly match this template (no extra words, no punctuation):\n"
        "Put the <OBJECT> into the <Object>\n"
        "- <OBJECT> MUST MUST MUST be CanonicalRef in the inventory.\n\n"
        "### Output Format: Strict JSON\n"
        "Your response must be a valid JSON object including a 'thought' field for step-by-step analysis, 'transitions' for the switch indices, and 'instructions' for the task labels.\n\n"
        "### Representative Examples\n"
        "**Example 1: Sorting (True Switch)**\n"
        "{\n"
        "  \"thought\": \"Frames 0-4: Robot carries the red car. Frame 5: Hand releases the red car into the brown basket and moves away. Frames 6-7: Hand reaches and grasps the gold car. Switch detected at 5.\",\n"
        "  \"transitions\": [5],\n"
        "  \"instructions\": [\"Put the red car into the brown basket\", \"Put the gold car into the brown basket\"]\n"
        "}\n\n"
        "**Example 2: Regrasping (False Switch, Same Object)**\n"
        "{\n"
        "  \"thought\": \"Frames 0-3: Robot grasps the red car. Frames 4-6: Robot regrips and adjusts the red car (same object) to align it for placement. Frame 7: Robot releases the red car into the brown basket. Object does not change, so no switch.\",\n"
        "  \"transitions\": [],\n"
        "  \"instructions\": [\"Put the red car into the brown basket\"]\n"
        "}\n\n"
        "**Example 3: Placement Adjustment (Continuous)**\n"
        "{\n"
        "  \"thought\": \"Frames 0-5: Robot places the kiwi into the black basket. Frames 6-12: Robot keeps adjusting the kiwi position inside the black basket without starting interaction with any other object. Continuous interaction with the same object, so no switch.\",\n"
        "  \"transitions\": [],\n"
        "  \"instructions\": [\"Put the kiwi into the black basket\"]\n"
        "}"
    )


'''
        "### Representative Examples\n"
        "**Example 1: Table Setting (True Switch)**\n"
        "{\n"
        "  \"thought\": \"Frames 0-5: Robot places a fork. Frame 6: Hand releases fork and moves to the spoon. Frame 7: Hand grasps spoon. Switch detected at 6.\",\n"
        "  \"transitions\": [6],\n"
        "  \"instructions\": [\"Place the fork\", \"Place the spoon\"]\n"
        "}\n\n"
        "**Example 2: Folding Laundry (False Switch - Same Object)**\n"
        "{\n"
        "  \"thought\": \"Frames 0-10: Robot folds the left sleeve of the black shirt. Frames 11-20: Robot folds the body of the **same** black shirt. Although the grasp changed, the object remains the same. The action is continuous.\",\n"
        "  \"transitions\": [],\n"
        "  \"instructions\": [\"Fold the black shirt\"]\n"
        "}\n\n"
        "**Example 3: Cleaning (Continuous)**\n"
        "{\n"
        "  \"thought\": \"Frames 0-15: Robot is wiping the counter. The motion is repetitive, but it is the same task. No switch.\",\n"
        "  \"transitions\": [],\n"
        "  \"instructions\": [\"Wipe the counter\"]\n"
'''